/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.mascota;

import ec.edu.ups.Modelo.Mascota;
import ec.edu.ups.controladores.ControladorMascota;
import ec.edu.ups.vista.VistaPrincipal;
import static ec.edu.ups.vista.mascota.CrearMascota.x;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Byron PC
 */
public class ActualizarMascota extends javax.swing.JInternalFrame {
private ControladorMascota controladorMascota;
public static String x;
private ResourceBundle mensajes;
public ImageIcon imgs[];
    /**
     * Creates new form ActualizarMascota
     */
    public ActualizarMascota(ControladorMascota controladorMascota, ResourceBundle mensajes) {
        initComponents();
        this.controladorMascota = controladorMascota;
        this.mensajes = mensajes;
         x="x";
         int a=VistaPrincipal.DesktopPane.getWidth()-this.getWidth();
        int b=VistaPrincipal.DesktopPane.getHeight()-this.getHeight();
        setLocation(a/2,b/2);
        setVisible(true);
        cambiaridioma(mensajes);
        imgs = new ImageIcon[6];
         imgs[0]= new ImageIcon("src/ec/edu/ups/imagenes/inicial.png");
        imgs[1]= new ImageIcon("src/ec/edu/ups/imagenes/caninos.png");
        imgs[2]= new ImageIcon("src/ec/edu/ups/imagenes/felinos.png");
        imgs[3]= new ImageIcon("src/ec/edu/ups/imagenes/reptil.png");
        imgs[4]= new ImageIcon("src/ec/edu/ups/imagenes/aves.png");
        imgs[5]= new ImageIcon("src/ec/edu/ups/imagenes/roedor.png");
        
        jLabel1.setIcon(imgs[0]);
    }
    
       public void cambiaridioma(ResourceBundle mensajes){
        jtitulo.setText(mensajes.getString("tituloM.modificar"));
        jingrese.setText(mensajes.getString("label.ingrese"));
        jdes.setText(mensajes.getString("label.de"));
        jnombre.setText(mensajes.getString("servicio.nombre"));        
        jpeso.setText(mensajes.getString("item.peso"));
        jedad.setText(mensajes.getString("label.edad"));
        jespecie.setText(mensajes.getString("label.especie"));
        btnbuscar.setText(mensajes.getString("boton.buscar"));
        btncancelar.setText(mensajes.getString("boton.cancelar"));
        btnactualizar.setText(mensajes.getString("boton.modificar"));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcodigo2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jnombre = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        jedad = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jpeso = new javax.swing.JLabel();
        txtpeso = new javax.swing.JTextField();
        jespecie = new javax.swing.JLabel();
        txtspecie = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jtitulo = new javax.swing.JLabel();
        jingrese = new javax.swing.JLabel();
        jdes = new javax.swing.JLabel();
        txtcodigoactu = new javax.swing.JTextField();
        btnactualizar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel3.setText("Ingrese el codigo");

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel6.setText("de su mascota:");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jnombre.setText("Nombre:");

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        jedad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jedad.setText("Edad:");

        jpeso.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jpeso.setText("Peso:");

        jespecie.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jespecie.setText("Especie:");

        txtspecie.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtspecieKeyPressed(evt);
            }
        });

        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpeso)
                    .addComponent(jedad)
                    .addComponent(jnombre)
                    .addComponent(jespecie))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtspecie)
                    .addComponent(txtnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(txtedad)
                    .addComponent(txtpeso))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnombre)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jedad)
                            .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jpeso)
                            .addComponent(txtpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jespecie)
                            .addComponent(txtspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jtitulo.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        jtitulo.setText("Actualizar Mascota");

        jingrese.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jingrese.setText("Ingrese el codigo");

        jdes.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jdes.setText("de su mascota:");

        btnactualizar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btncancelar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        btnbuscar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnbuscar.setText("Buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtitulo)
                        .addContainerGap(79, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jingrese)
                            .addComponent(jdes))
                        .addGap(40, 40, 40)
                        .addComponent(txtcodigoactu, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnbuscar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnactualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btncancelar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jingrese)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdes, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtcodigoactu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnbuscar)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnactualizar)
                    .addComponent(btncancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        // TODO add your handling code here:
         int codigo = Integer.parseInt(txtcodigoactu.getText());
        Mascota mascota = controladorMascota.read(codigo);
        if (mascota == null) {
            JOptionPane.showMessageDialog(null, "Su mascota no ha sido registrada");
        } else {
            txtedad.setText(Integer.toString(mascota.getEdad()));
            txtnombre.setText(mascota.getNombre());
            txtpeso.setText(Double.toString(mascota.getPeso()));
            txtspecie.setText(mascota.getEspecie());
            checar();
        }
    }//GEN-LAST:event_btnbuscarActionPerformed
public void checar(){
    if("canino".equals(txtspecie.getText())){
        jLabel1.setIcon(imgs[1]);
    }
    if("felino".equals(txtspecie.getText())){
        jLabel1.setIcon(imgs[2]);
    }
    if("reptil".equals(txtspecie.getText())){
        jLabel1.setIcon(imgs[3]);
    }
    if("ave".equals(txtspecie.getText())){
        jLabel1.setIcon(imgs[4]);
    }
    if("roedor".equals(txtspecie.getText())){
        jLabel1.setIcon(imgs[5]);
    }
}
    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        // TODO add your handling code here:
        Mascota mascota = new Mascota();
       mascota.setCodigo(Integer.parseInt(txtcodigoactu.getText()));
        mascota.setEdad(Integer.parseInt(txtedad.getText()));
        mascota.setNombre(txtnombre.getText());
        mascota.setPeso(Double.parseDouble(txtpeso.getText()));
        mascota.setEspecie(txtspecie.getText());
        controladorMascota.update(mascota);
        txtcodigoactu.setText("");
        txtedad.setText("");
        txtnombre.setText("");
        txtpeso.setText("");
        txtspecie.setText("");
        jLabel1.setIcon(null);
        JOptionPane.showMessageDialog(null, "Mascota Actualizada");
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
   this.setVisible(false);
   x=null;
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtspecieKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtspecieKeyPressed
        // TODO add your handling code here:
        checar();
    }//GEN-LAST:event_txtspecieKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jdes;
    private javax.swing.JLabel jedad;
    private javax.swing.JLabel jespecie;
    private javax.swing.JLabel jingrese;
    private javax.swing.JLabel jnombre;
    private javax.swing.JLabel jpeso;
    private javax.swing.JLabel jtitulo;
    private javax.swing.JTextField txtcodigo2;
    private javax.swing.JTextField txtcodigoactu;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtpeso;
    private javax.swing.JTextField txtspecie;
    // End of variables declaration//GEN-END:variables
}
