/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.factura;

import ec.edu.ups.Modelo.Cliente;
import ec.edu.ups.Modelo.FDetalle;
import ec.edu.ups.Modelo.FFactura;
import ec.edu.ups.Modelo.Mascota;
import ec.edu.ups.Modelo.Servicio;
import ec.edu.ups.Modelo.Veterinario;
import ec.edu.ups.controladores.ControladorCliente;
import ec.edu.ups.controladores.ControladorFacDetalle;
import ec.edu.ups.controladores.ControladorFactura;
import ec.edu.ups.controladores.ControladorMascota;
import ec.edu.ups.controladores.ControladorServicio;
import ec.edu.ups.controladores.ControladorVeterinario;
import ec.edu.ups.vista.VistaPrincipal;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.List;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Domenica Cañizares
 */
public class FacturaCrear extends javax.swing.JInternalFrame {

    /**
     * Creates new form FacturaCrear
     */
    public static String x;

    private ControladorFactura controladorFactura;
    private ControladorCliente controladorCliente;
    private ControladorVeterinario controladorVeterinario;
    private ControladorMascota controladorMascota;
    private ControladorServicio controladorServicio;
    private ControladorFacDetalle controladorFDetalle;

    private FFactura factura;
    private Servicio servicio;
    private FDetalle facDet;
    private Mascota mascota;
    private Cliente cliente;
    private Veterinario veterinario;

    private Date fecha;

    private int contador;
    private double totalCP, subtotal, iva, total;
    private DefaultTableModel tablaF;

    private ResourceBundle mensajes;

    public FacturaCrear(ResourceBundle mensajes, ControladorFactura controladorFactura, ControladorFacDetalle controladorFDetalle, ControladorCliente controladorCliente, ControladorVeterinario controladorVeterinario, ControladorMascota controladorMascota, ControladorServicio controladorServicio) {
        initComponents();

        this.controladorFactura = controladorFactura;
        this.controladorFDetalle = controladorFDetalle;
        this.controladorCliente = controladorCliente;
        this.controladorVeterinario = controladorVeterinario;
        this.controladorMascota = controladorMascota;
        this.controladorServicio = controladorServicio;

        this.mensajes = mensajes;
        cambiarIdioma(mensajes);

        this.factura = new FFactura();

        totalCP = 0;
        subtotal = 0;
        iva = 0;
        total = 0;
        tablaF = null;
        servicio = null;
        contador = 0;

        int ruc = this.controladorFactura.getCodigo() + 1;
        txtRuc.setText(String.valueOf(ruc));
        txtFecha.setText(controladorFactura.getFecha());

        x = "x";

        //centrar pantalla
        int a = VistaPrincipal.DesktopPane.getWidth() - this.getWidth();
        int b = VistaPrincipal.DesktopPane.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        lblCedC = new javax.swing.JLabel();
        txtCedC = new javax.swing.JTextField();
        btnBuscarCF = new javax.swing.JButton();
        lblCodC = new javax.swing.JLabel();
        txtCodC = new javax.swing.JTextField();
        lblNomC = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        lblTelC = new javax.swing.JLabel();
        txtTelC = new javax.swing.JTextField();
        txtApeC = new javax.swing.JTextField();
        lblApeC = new javax.swing.JLabel();
        lblDirC = new javax.swing.JLabel();
        txtDirC = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblNomV = new javax.swing.JLabel();
        txtNomV = new javax.swing.JTextField();
        lblApeV = new javax.swing.JLabel();
        txtApeV = new javax.swing.JTextField();
        lblCedV = new javax.swing.JLabel();
        txtCedV = new javax.swing.JTextField();
        btnBuscarVF = new javax.swing.JButton();
        lblCodV = new javax.swing.JLabel();
        txtCodV = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        lblCodM = new javax.swing.JLabel();
        txtCodM = new javax.swing.JTextField();
        txtNomM = new javax.swing.JTextField();
        lblNomM = new javax.swing.JLabel();
        txtEdadM = new javax.swing.JTextField();
        lblEdadM = new javax.swing.JLabel();
        btnBuscarMF = new javax.swing.JButton();
        lblPesoM = new javax.swing.JLabel();
        txtPesoM = new javax.swing.JTextField();
        txtEspecie = new javax.swing.JTextField();
        lblEspecie = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServF = new javax.swing.JTable();
        btnCrear = new javax.swing.JButton();
        lblSub = new javax.swing.JLabel();
        txtSubtotal = new javax.swing.JTextField();
        lblIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        lblTot = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnCancelarF = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCedC.setBackground(new java.awt.Color(255, 255, 255));
        lblCedC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCedC.setText("Cedula Cliente");

        txtCedC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        btnBuscarCF.setText("Buscar");
        btnBuscarCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCFActionPerformed(evt);
            }
        });

        lblCodC.setBackground(new java.awt.Color(255, 255, 255));
        lblCodC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCodC.setText("Codigo Cliente");

        txtCodC.setEditable(false);
        txtCodC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCodC.setEnabled(false);

        lblNomC.setBackground(new java.awt.Color(255, 255, 255));
        lblNomC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNomC.setText("Nombre Cliente");

        txtNomC.setEditable(false);
        txtNomC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtNomC.setEnabled(false);

        lblTelC.setBackground(new java.awt.Color(255, 255, 255));
        lblTelC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTelC.setText("Telefono Cliente");

        txtTelC.setEditable(false);
        txtTelC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTelC.setEnabled(false);

        txtApeC.setEditable(false);
        txtApeC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtApeC.setEnabled(false);

        lblApeC.setBackground(new java.awt.Color(255, 255, 255));
        lblApeC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblApeC.setText("Apellido Cliente");

        lblDirC.setBackground(new java.awt.Color(255, 255, 255));
        lblDirC.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblDirC.setText("Direccion Cliente");

        txtDirC.setEditable(false);
        txtDirC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtDirC.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblTelC)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNomC)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblCedC)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnBuscarCF)
                        .addGap(18, 18, 18)
                        .addComponent(lblCodC)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblApeC)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtApeC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lblDirC)
                            .addGap(18, 18, 18)
                            .addComponent(txtDirC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedC)
                    .addComponent(txtCedC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCF)
                    .addComponent(lblCodC)
                    .addComponent(txtCodC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblApeC)
                        .addComponent(txtApeC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomC)
                        .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDirC)
                        .addComponent(txtDirC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelC)
                        .addComponent(txtTelC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblNomV.setBackground(new java.awt.Color(255, 255, 255));
        lblNomV.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNomV.setText("Nombre Veterinario");

        txtNomV.setEditable(false);
        txtNomV.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtNomV.setEnabled(false);

        lblApeV.setBackground(new java.awt.Color(255, 255, 255));
        lblApeV.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblApeV.setText("Apellido Veterinario");

        txtApeV.setEditable(false);
        txtApeV.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtApeV.setEnabled(false);

        lblCedV.setBackground(new java.awt.Color(255, 255, 255));
        lblCedV.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCedV.setText("Cedula Veterinario");

        txtCedV.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        btnBuscarVF.setText("Buscar");
        btnBuscarVF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarVFActionPerformed(evt);
            }
        });

        lblCodV.setBackground(new java.awt.Color(255, 255, 255));
        lblCodV.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCodV.setText("Codigo Veterinario");

        txtCodV.setEditable(false);
        txtCodV.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCodV.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblNomV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNomV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(lblApeV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApeV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCedV)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarVF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCodV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodV, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodV)
                        .addComponent(txtCodV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedV)
                        .addComponent(txtCedV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarVF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomV)
                    .addComponent(txtNomV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApeV)
                    .addComponent(txtApeV, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCodM.setBackground(new java.awt.Color(255, 255, 255));
        lblCodM.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblCodM.setText("Codigo Mascota");

        txtCodM.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        txtNomM.setEditable(false);
        txtNomM.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtNomM.setEnabled(false);

        lblNomM.setBackground(new java.awt.Color(255, 255, 255));
        lblNomM.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblNomM.setText("Nombre Mascota");

        txtEdadM.setEditable(false);
        txtEdadM.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtEdadM.setEnabled(false);

        lblEdadM.setBackground(new java.awt.Color(255, 255, 255));
        lblEdadM.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblEdadM.setText("Edad Mascota");

        btnBuscarMF.setText("Buscar");
        btnBuscarMF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMFActionPerformed(evt);
            }
        });

        lblPesoM.setBackground(new java.awt.Color(255, 255, 255));
        lblPesoM.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblPesoM.setText("Peso Mascota");

        txtPesoM.setEditable(false);
        txtPesoM.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtPesoM.setEnabled(false);

        txtEspecie.setEditable(false);
        txtEspecie.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtEspecie.setEnabled(false);

        lblEspecie.setBackground(new java.awt.Color(255, 255, 255));
        lblEspecie.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblEspecie.setText("Especie Mascota");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblNomM)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblCodM)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(btnBuscarMF)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEdadM)
                                .addGap(18, 18, 18)
                                .addComponent(txtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(lblPesoM)
                                .addGap(18, 18, 18)
                                .addComponent(txtPesoM, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(lblEspecie)
                        .addGap(18, 18, 18)
                        .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEdadM)
                        .addComponent(txtEdadM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodM)
                        .addComponent(txtCodM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnBuscarMF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPesoM)
                        .addComponent(txtPesoM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomM)
                        .addComponent(txtNomM, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEspecie)
                    .addComponent(txtEspecie, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblRuc.setBackground(new java.awt.Color(255, 255, 255));
        lblRuc.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblRuc.setText("RUC Factura");

        txtRuc.setEditable(false);
        txtRuc.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtRuc.setEnabled(false);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblFecha.setText("Fecha");

        lblTitulo.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        lblTitulo.setText("Crear Factura");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtFecha.setEnabled(false);

        tblServF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "0", null, null, null}
            },
            new String [] {
                "codigo", "cantidad", "nombre", "precio u", "totalCP"
            }
        ));
        tblServF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblServFKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblServF);

        btnCrear.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        lblSub.setBackground(new java.awt.Color(255, 255, 255));
        lblSub.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblSub.setText("Subtotal");

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtSubtotal.setEnabled(false);

        lblIva.setBackground(new java.awt.Color(255, 255, 255));
        lblIva.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblIva.setText("I.V.A");

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtIva.setEnabled(false);

        lblTot.setBackground(new java.awt.Color(255, 255, 255));
        lblTot.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblTot.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTotal.setEnabled(false);

        btnCancelarF.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        btnCancelarF.setText("Cancelar");
        btnCancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRuc)
                                .addGap(18, 18, 18)
                                .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblFecha)
                                .addGap(18, 18, 18)
                                .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblTitulo))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCrear)
                                .addGap(34, 34, 34)
                                .addComponent(btnCancelarF)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSub)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(27, 27, 27)
                                            .addComponent(lblIva)
                                            .addGap(16, 16, 16)
                                            .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(25, 25, 25)
                                            .addComponent(lblTot)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(lblTitulo)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuc)
                            .addComponent(lblFecha))))
                .addGap(4, 4, 4)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblSub))
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblIva)
                        .addComponent(btnCrear)
                        .addComponent(btnCancelarF)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblTot))
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCFActionPerformed

        String cedula = txtCedC.getText();
        cliente = controladorCliente.read1(cedula);

        if (cliente == null) {
            JOptionPane.showMessageDialog(null, "Cedula no Existe");
        } else {
            //txtCodC.setText(Integer.toString(cliente.getCodigo()));
            txtNomC.setText(cliente.getNombre());
            txtApeC.setText(cliente.getApellido());
            txtDirC.setText(cliente.getDireccion());
            txtTelC.setText(cliente.getTelefono());
        }
    }//GEN-LAST:event_btnBuscarCFActionPerformed

    private void btnBuscarVFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarVFActionPerformed

        String cedulaV = txtCedV.getText();
        veterinario = controladorVeterinario.readCedula(cedulaV);

        if (veterinario == null) {
            JOptionPane.showMessageDialog(this, "Cedula no encontrada");
        } else {
            txtCodV.setText(Integer.toString(veterinario.getCodigo()));
            txtNomV.setText(veterinario.getNombre());
            txtApeV.setText(veterinario.getApellido());
        }

    }//GEN-LAST:event_btnBuscarVFActionPerformed

    private void btnBuscarMFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMFActionPerformed

        int codigo = Integer.parseInt(txtCodM.getText());
        mascota = controladorMascota.read(codigo);
        if (mascota == null) {
            JOptionPane.showMessageDialog(null, "Codigo no encontrado");
        } else {
            txtEdadM.setText(Integer.toString(mascota.getEdad()));
            txtNomM.setText(mascota.getNombre());
            txtPesoM.setText(Double.toString(mascota.getPeso()));
            txtEspecie.setText(mascota.getEspecie());
        }
    }//GEN-LAST:event_btnBuscarMFActionPerformed

    private void tblServFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServFKeyReleased
        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            int fila = tblServF.getSelectedRow();
            int columna = tblServF.getSelectedColumn();
            int codigoServ = 0;

            Object[] datos1 = {"", 0, "", "", ""};

            if (columna == 0) {
                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                servicio = controladorServicio.read(codigoServ);

                int cant = Integer.parseInt(tblServF.getValueAt(fila, 1).toString());

                tablaF = (DefaultTableModel) tblServF.getModel();
                tablaF.removeRow(fila);
                totalCP = cant * servicio.getPrecio();

                Object[] datos = {codigoServ,
                    cant,
                    servicio.getNombreservicio(),
                    servicio.getPrecio(),
                    totalCP
                };

                tablaF.addRow(datos);
                tablaF.addRow(datos1);
            } else if (columna == 1) {

                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna - 1).toString());
                int cant = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                tablaF.removeRow(fila);
                tablaF.removeRow(tblServF.getRowCount() - 1);

                totalCP = cant * servicio.getPrecio();

                Object[] datos = {codigoServ,
                    cant,
                    servicio.getNombreservicio(),
                    servicio.getPrecio(),
                    totalCP
                };

                tablaF.addRow(datos);
                tablaF.addRow(datos1);

            }

            subtotal = subtotal + totalCP;
            txtSubtotal.setText(String.valueOf(subtotal));

            iva = subtotal * 0.12;
            txtIva.setText(String.valueOf(iva));

            total = subtotal + iva;
            txtTotal.setText(String.valueOf(total));

        }
    }//GEN-LAST:event_tblServFKeyReleased

    public void llenarDatos() {
        DefaultTableModel modeloP = (DefaultTableModel) tblServF.getModel();
        List<FDetalle> lista = factura.getDetalle();

        while (contador < lista.size()) {
            Object[] datos2 = {factura.getDetalle().get(contador).getCodigo(),
                lista.get(contador).getCantidad(),
                lista.get(contador).getServ().getNombreservicio(),
                lista.get(contador).getServ().getPrecio(),
                lista.get(contador).getTotalCP()
            };
            modeloP.addRow(datos2);
            contador++;
        }
        /*
         calcularSubtotal();
         txtSubtotal.setText(Double.toString(factura.getSubtotal()));
         calcularTotal();
         txtTotal.setText(Double.toString(factura.getTotal()));
         */
    }

    public void calcularSubtotal() {
        double sub = 0;
        for (int i = 0; i < factura.getDetalle().size(); i++) {
            sub += factura.getDetalle().get(i).getTotalCP();
        }
        factura.setSubtotal(sub);
    }

    public void calcularTotal() {
        double tot = factura.getSubtotal() + factura.getIva();
        factura.setTotal(tot);
    }

    public void vaciarDatos() {

        txtApeC.setText("");
        txtApeV.setText("");
        txtCedC.setText("");
        txtCedV.setText("");
        txtCodC.setText("");
        txtCodM.setText("");
        txtCodV.setText("");
        txtDirC.setText("");
        txtEdadM.setText("");
        txtFecha.setText("");
        txtIva.setText("");
        txtNomC.setText("");
        txtNomM.setText("");
        txtNomV.setText("");
        txtPesoM.setText("");
        txtSubtotal.setText("");
        txtTelC.setText("");
        txtTotal.setText("");

    }

    public void vaciarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tblServF.getModel();
        int filas = tblServF.getRowCount();
        for (int i = 0; i < filas; i++) {
            modelo.removeRow(0);
        }

        Object[] datos1 = {"", 0, "", "", ""};
        tablaF.addRow(datos1);

    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        //titulo
        lblTitulo.setText(mensajes.getString("tituloF.crear"));

        //Veterinario
        lblCedV.setText(mensajes.getString("labelF.cedV"));
        lblCodV.setText(mensajes.getString("labelF.codV"));
        lblNomV.setText(mensajes.getString("labelF.nomV"));
        lblApeV.setText(mensajes.getString("labelF.apeV"));

        //Cliente
        lblCedC.setText(mensajes.getString("labelF.cedC"));
        lblCodC.setText(mensajes.getString("labelF.codC"));
        lblNomC.setText(mensajes.getString("labelF.nomC"));
        lblApeC.setText(mensajes.getString("labelF.apeC"));
        lblDirC.setText(mensajes.getString("labelF.dirC"));
        lblTelC.setText(mensajes.getString("labelF.telC"));

        //Mascota
        lblCodM.setText(mensajes.getString("labelF.codM"));
        lblNomM.setText(mensajes.getString("labelF.nomM"));
        lblEdadM.setText(mensajes.getString("labelF.edadM"));
        lblPesoM.setText(mensajes.getString("labelF.pesoM"));

        //Tabla
        JTableHeader tableHeader = tblServF.getTableHeader();
        TableColumnModel tableColumnModel = tableHeader.getColumnModel();

        TableColumn tableColum;

        tableColum = tableColumnModel.getColumn(0);
        tableColum.setHeaderValue(mensajes.getString("label.codigo"));

        tableColum = tableColumnModel.getColumn(1);
        tableColum.setHeaderValue(mensajes.getString("labelFD.cant"));

        tableColum = tableColumnModel.getColumn(2);
        tableColum.setHeaderValue(mensajes.getString("servicio.nombre"));

        tableColum = tableColumnModel.getColumn(3);
        tableColum.setHeaderValue(mensajes.getString("servicio.precio"));

        tableColum = tableColumnModel.getColumn(4);
        tableColum.setHeaderValue(mensajes.getString("labelF.tot"));

        //factura
        lblSub.setText(mensajes.getString("labelF.sub"));
        lblIva.setText(mensajes.getString("labelF.iva"));
        lblTot.setText(mensajes.getString("labelF.tot"));

        //boton
        btnBuscarCF.setText(mensajes.getString("boton.buscar"));
        btnBuscarMF.setText(mensajes.getString("boton.buscar"));
        btnBuscarVF.setText(mensajes.getString("boton.buscar"));
        btnCrear.setText(mensajes.getString("boton.crear"));
        btnCancelarF.setText(mensajes.getString("boton.cancelar"));

    }

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        //obtener fecha
        fecha = new Date();

        //obtener clases
        String cedulaC = txtCedC.getText();
        cliente = controladorCliente.readCedula(cedulaC);

        String cedulaV = txtCedV.getText();
        veterinario = controladorVeterinario.readCedula(cedulaV);

        int codigoM = Integer.parseInt(txtCodM.getText());
        mascota = controladorMascota.read(codigoM);

        //agregarDatos
        factura.setFecha(fecha);

        //clases
        factura.setVet(veterinario);
        factura.setCli(cliente);
        factura.setMasc(mascota);

        //facDetalle
        for (int i = 0; i < tblServF.getRowCount() - 1; i++) {
            System.out.println("i " + i);
            facDet = new FDetalle();

            double cant = Integer.parseInt(tblServF.getValueAt(i, 1).toString());
            int cant1 = (int) cant;
            facDet.setCantidad(cant1);

            //facDet.setCodigo(Integer.parseInt(tblServF.getValueAt(i, 0).toString()));
            //int codigoS = ;
            //facDet.setServ(controladorServicio.read(Integer.parseInt(tblServF.getValueAt(i, 0).toString())));
            facDet.setServ(controladorServicio.read(Integer.parseInt(tblServF.getValueAt(i, 0).toString())));
            factura.añadirFacDetalle(facDet);
//            controladorFDetalle.create(facDet);

        }

        llenarDatos();
        //factura
        factura.setSubtotal(subtotal);
        factura.setIva(iva);
        factura.setTotal(total);

        controladorFactura.create(factura);
        JOptionPane.showMessageDialog(this, "Factura Creada");
        System.out.println("factura \n" + factura.toString());

        txtRuc.setText(Integer.toString(controladorFactura.getCodigo()));
        factura.setRuc(Integer.parseInt(txtRuc.getText()));

        contador = 0;

        vaciarDatos();
        vaciarTabla();

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFActionPerformed
        // TODO add your handling code here:
        x = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarCF;
    private javax.swing.JButton btnBuscarMF;
    private javax.swing.JButton btnBuscarVF;
    private javax.swing.JButton btnCancelarF;
    private javax.swing.JButton btnCrear;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApeC;
    private javax.swing.JLabel lblApeV;
    private javax.swing.JLabel lblCedC;
    private javax.swing.JLabel lblCedV;
    private javax.swing.JLabel lblCodC;
    private javax.swing.JLabel lblCodM;
    private javax.swing.JLabel lblCodV;
    private javax.swing.JLabel lblDirC;
    private javax.swing.JLabel lblEdadM;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNomC;
    private javax.swing.JLabel lblNomM;
    private javax.swing.JLabel lblNomV;
    private javax.swing.JLabel lblPesoM;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTelC;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTot;
    private javax.swing.JTable tblServF;
    private javax.swing.JTextField txtApeC;
    private javax.swing.JTextField txtApeV;
    private javax.swing.JTextField txtCedC;
    private javax.swing.JTextField txtCedV;
    private javax.swing.JTextField txtCodC;
    private javax.swing.JTextField txtCodM;
    private javax.swing.JTextField txtCodV;
    private javax.swing.JTextField txtDirC;
    private javax.swing.JTextField txtEdadM;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtNomM;
    private javax.swing.JTextField txtNomV;
    private javax.swing.JTextField txtPesoM;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelC;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
