/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.servicio;

import ec.edu.ups.Modelo.Servicio;
import ec.edu.ups.controladores.ControladorServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private ControladorServicio controladorservicio;
    public CrearServicio(ControladorServicio controladorservicio) {
        initComponents();
    this.controladorservicio = controladorservicio;
     txtcp.setText(Integer.toString(this.controladorservicio.getCodigo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        txtp = new javax.swing.JTextField();
        JCE = new javax.swing.JLabel();
        txtnp = new javax.swing.JTextField();
        JN = new javax.swing.JLabel();
        LCODIGO = new javax.swing.JLabel();
        txtcp = new javax.swing.JTextField();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(10, 10, 10, 10, new java.awt.Color(204, 255, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("CREAR SERVICIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 220, 50));

        cancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar.setForeground(new java.awt.Color(0, 255, 204));
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 40));

        Aceptar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Aceptar.setForeground(new java.awt.Color(0, 255, 204));
        Aceptar.setText("Aceptar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 150, 40));

        txtp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpActionPerformed(evt);
            }
        });
        jPanel1.add(txtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 220, 50));

        JCE.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JCE.setText("PRECIO:");
        JCE.setToolTipText("");
        jPanel1.add(JCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

        txtnp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpActionPerformed(evt);
            }
        });
        jPanel1.add(txtnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 220, 50));

        JN.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JN.setText("NOMBRE:");
        jPanel1.add(JN, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, 30));

        LCODIGO.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LCODIGO.setText("CODIGO:");
        jPanel1.add(LCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 120, 30));

        txtcp.setEditable(false);
        txtcp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 220, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 480, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        Servicio servicio =new Servicio();
        System.out.println(servicio.getCodigo());
        servicio.setCodigo(Integer.parseInt(txtcp.getText()));
        servicio.setNombreservicio(txtnp.getText());
        servicio.setPrecio(Double.parseDouble(txtp.getText()));
        controladorservicio.create(servicio);

        ////////limpiar
        txtnp.setText("");
        txtp.setText("");
        txtcp.setText(String.valueOf(this.controladorservicio.getCodigo()));
        JOptionPane.showMessageDialog(this, "Servicio creado exitosamente!!", "Crear servicio" , JOptionPane.OK_OPTION);
    }//GEN-LAST:event_AceptarActionPerformed

    private void txtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpActionPerformed

    private void txtnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JLabel JCE;
    private javax.swing.JLabel JN;
    private javax.swing.JLabel LCODIGO;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtnp;
    private javax.swing.JTextField txtp;
    // End of variables declaration//GEN-END:variables
}
