/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.servicio;

import ec.edu.ups.Modelo.Servicio;
import ec.edu.ups.controladores.ControladorServicio;
import ec.edu.ups.vista.VistaPrincipal;
import static ec.edu.ups.vista.cliente.CrearCliente.x;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    private ControladorServicio controladorservicio;
    public static String x;
    private ResourceBundle mensajes;

    public CrearServicio(ControladorServicio controladorservicio, ResourceBundle mensajes) {
        initComponents();
        this.controladorservicio = controladorservicio;
        txtcp.setText(Integer.toString(this.controladorservicio.getCodigo()));
        x = "x";
        int a = VistaPrincipal.DesktopPane.getWidth() - this.getWidth();
        int b = VistaPrincipal.DesktopPane.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true);
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        labels.setText(mensajes.getString("titulos.crear"));
        labelc.setText(mensajes.getString("servicio.codigo"));
        labeln.setText(mensajes.getString("servicio.nombre"));
        labelp.setText(mensajes.getString("servicio.precio"));

        bc.setText(mensajes.getString("servicio.bcrear"));
        bca.setText(mensajes.getString("servicio.bcancelar"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bca = new javax.swing.JButton();
        bc = new javax.swing.JButton();
        txtp = new javax.swing.JTextField();
        labelp = new javax.swing.JLabel();
        txtnp = new javax.swing.JTextField();
        labeln = new javax.swing.JLabel();
        labelc = new javax.swing.JLabel();
        txtcp = new javax.swing.JTextField();
        labels = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bca.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        bca.setText("Cancelar");
        bca.setBorder(null);
        bca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaActionPerformed(evt);
            }
        });
        jPanel1.add(bca, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 150, 40));

        bc.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        bc.setText("Crear");
        bc.setBorder(null);
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });
        jPanel1.add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 150, 40));

        txtp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpActionPerformed(evt);
            }
        });
        jPanel1.add(txtp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 220, 40));

        labelp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelp.setText("PRECIO:");
        labelp.setToolTipText("");
        jPanel1.add(labelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, 40));

        txtnp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtnp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtnp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnpActionPerformed(evt);
            }
        });
        jPanel1.add(txtnp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 220, 40));

        labeln.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeln.setText("NOMBRE:");
        jPanel1.add(labeln, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, 40));

        labelc.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelc.setText("CODIGO:");
        jPanel1.add(labelc, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, 40));

        txtcp.setEditable(false);
        txtcp.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 220, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 480, 270));

        labels.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        labels.setText("CREAR SERVICIO");
        getContentPane().add(labels, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 420, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
        x = null;
    }//GEN-LAST:event_bcaActionPerformed

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:
        Servicio servicio = new Servicio();
        System.out.println(servicio.getCodigo());
        servicio.setCodigo(Integer.parseInt(txtcp.getText()));
        servicio.setNombreservicio(txtnp.getText());
        servicio.setPrecio(Double.parseDouble(txtp.getText()));
        controladorservicio.create(servicio);

        ////////limpiar
        txtnp.setText("");
        txtp.setText("");
        txtcp.setText(String.valueOf(this.controladorservicio.getCodigo()));
        JOptionPane.showMessageDialog(this, "Servicio creado exitosamente!!", "Crear servicio", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_bcActionPerformed

    private void txtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpActionPerformed

    private void txtnpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnpActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        // TODO add your handling code here:
        x = null;
    }//GEN-LAST:event_formInternalFrameClosed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bc;
    private javax.swing.JButton bca;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelc;
    private javax.swing.JLabel labeln;
    private javax.swing.JLabel labelp;
    private javax.swing.JLabel labels;
    private javax.swing.JTextField txtcp;
    private javax.swing.JTextField txtnp;
    private javax.swing.JTextField txtp;
    // End of variables declaration//GEN-END:variables
}
