/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.servicio;

import ec.edu.ups.Modelo.Servicio;
import ec.edu.ups.controladores.ControladorServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class EliminarServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarServicio
     */
    private ControladorServicio controladorservicio;
    public EliminarServicio(ControladorServicio controladorservicio) {
        initComponents();
        this.controladorservicio = controladorservicio;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelar = new javax.swing.JButton();
        Aceptar = new javax.swing.JButton();
        txtprecio = new javax.swing.JTextField();
        JCE = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        JN = new javax.swing.JLabel();
        LCODIGO = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        BE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setAutoscrolls(true);
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 150, 40));

        Aceptar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        Aceptar.setText("Buscar");
        Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 150, 40));

        txtprecio.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecioActionPerformed(evt);
            }
        });
        jPanel1.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 210, 40));

        JCE.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JCE.setText("PRECIO:");
        JCE.setToolTipText("");
        jPanel1.add(JCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, 40));

        txtnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, 40));

        JN.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        JN.setText("NOMBRE:");
        jPanel1.add(JN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, 40));

        LCODIGO.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        LCODIGO.setText("CODIGO:");
        jPanel1.add(LCODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 40));

        txtcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 210, 40));

        BE.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        BE.setText("Eliminar");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });
        jPanel1.add(BE, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, 140, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 500, 320));

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        jLabel1.setText("ELIMINAR SERVICIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 500, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtcodigo.getText());
        Servicio buscarProducto = controladorservicio.read(codigo);
        txtnombre.setText(buscarProducto.getNombreservicio());
        txtprecio.setText(String.valueOf(buscarProducto.getPrecio()));
    }//GEN-LAST:event_AceptarActionPerformed

    private void txtprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecioActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtcodigo.getText());
        controladorservicio.delete(codigo);
        JOptionPane.showMessageDialog(this, "Servici eliminado exitosamente!!", "eliminar servicio" , JOptionPane.OK_OPTION);
       txtcodigo.setText("");
        txtnombre.setText("");
        txtprecio.setText("");
    }//GEN-LAST:event_BEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar;
    private javax.swing.JButton BE;
    private javax.swing.JLabel JCE;
    private javax.swing.JLabel JN;
    private javax.swing.JLabel LCODIGO;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtprecio;
    // End of variables declaration//GEN-END:variables
}
