/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.servicio;

import ec.edu.ups.Modelo.Servicio;
import ec.edu.ups.controladores.ControladorServicio;
import ec.edu.ups.vista.VistaPrincipal;
import java.util.ResourceBundle;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Carlos
 */
public class ListaServicio extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListaServicio
     */
    private ControladorServicio controladorservicio;
        public static String x;
        private ResourceBundle mensajes;
    public ListaServicio(ControladorServicio controladorservicio, ResourceBundle mensajes) {
        initComponents();
        x="x";
         int a=VistaPrincipal.DesktopPane.getWidth()-this.getWidth();
        int b=VistaPrincipal.DesktopPane.getHeight()-this.getHeight();
        setLocation(a/2,b/2);
        setVisible(true);
        this.controladorservicio = controladorservicio;
         llenarDatos();
         
         this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }
public void llenarDatos() {
        DefaultTableModel modelo = (DefaultTableModel) tablaservicio.getModel();
        Set<Servicio> lista = controladorservicio.getLista();
        for (Servicio servicio : lista){
            Object[] datos = {servicio.getCodigo(),
                servicio.getNombreservicio(),
                  servicio.getPrecio()};
            modelo.addRow(datos);
        }
}
 public void cambiarIdioma(ResourceBundle mensajes) {
        labell.setText(mensajes.getString("titulos.lista"));
        JTableHeader tableHeader = tablaservicio.getTableHeader();
        TableColumnModel tableColumnModel = tableHeader.getColumnModel();
        TableColumn tableColumn;
        tableColumn = tableColumnModel.getColumn(0);
        tableColumn.setHeaderValue(mensajes.getString("servicio.codigo"));
        tableColumn = tableColumnModel.getColumn(1);
        tableColumn.setHeaderValue(mensajes.getString("servicio.nombre"));
        tableColumn = tableColumnModel.getColumn(2);
        
        tableColumn.setHeaderValue(mensajes.getString("servicio.precio"));
      
        tableHeader.repaint();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaservicio = new javax.swing.JTable();
        labell = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaservicio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        tablaservicio.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        tablaservicio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ));
        tablaservicio.setEnabled(false);
        tablaservicio.setGridColor(new java.awt.Color(102, 204, 0));
        jScrollPane1.setViewportView(tablaservicio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 580, 340));

        labell.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        labell.setText("LISTA DE SERVICIO");
        getContentPane().add(labell, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 460, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labell;
    private javax.swing.JTable tablaservicio;
    // End of variables declaration//GEN-END:variables
}
