/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.veterinario;

import ec.edu.ups.Modelo.Veterinario;
import ec.edu.ups.controladores.ControladorVeterinario;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class CrearVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearVeterinario
     */
    private ControladorVeterinario controladorveterinario;

    public CrearVeterinario(ControladorVeterinario controladorveterinario) {
        initComponents();
        this.controladorveterinario = controladorveterinario;
        txtcodigo.setText(Integer.toString(this.controladorveterinario.getCodigo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        labelcodigo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        labelnombre = new javax.swing.JLabel();
        labelapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        labelcedula = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        labeledad = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        labeldireccion = new javax.swing.JLabel();
        labelgenero = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        botoncrearcliente = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcodigo.setEnabled(false);
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 162, 28));

        labelcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcodigo.setText("Código:");
        jPanel1.add(labelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, 30));

        txtnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtnombre.setToolTipText("");
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 200, 31));

        labelnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelnombre.setText("Nombre:");
        jPanel1.add(labelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        labelapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelapellido.setText("Apellido:");
        jPanel1.add(labelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, 30));

        txtapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtapellido.setToolTipText("");
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 203, 29));

        txtcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcedula.setToolTipText("");
        txtcedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 196, 30));

        labelcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcedula.setText("Cedula:");
        jPanel1.add(labelcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, 30));

        txtedad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtedad.setToolTipText("");
        txtedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 61, 29));

        labeledad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeledad.setText("Edad:");
        jPanel1.add(labeledad, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, -1, 30));

        txtsueldo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtsueldo.setToolTipText("");
        txtsueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 196, 30));

        labeldireccion.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeldireccion.setText("Sueldo:");
        jPanel1.add(labeldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, 30));

        labelgenero.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelgenero.setText("Titulo:");
        jPanel1.add(labelgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, 30));

        txttitulo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txttitulo.setToolTipText("");
        txttitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 196, 31));

        botoncrearcliente.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        botoncrearcliente.setText("Crear ");
        botoncrearcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncrearclienteActionPerformed(evt);
            }
        });
        jPanel1.add(botoncrearcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 126, -1));

        cancelar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 150, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 620, 260));

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        jLabel1.setText("CREAR VETERINARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoncrearclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncrearclienteActionPerformed
        // TODO add your handling code here:
        Veterinario veterinario = new Veterinario();
        veterinario.setNombre(txtnombre.getText());
        veterinario.setApellido(txtapellido.getText());
        veterinario.setCedula(txtcedula.getText());
        veterinario.setEdad(Integer.parseInt(txtedad.getText()));
        veterinario.setSueldo(Double.parseDouble(txtsueldo.getText()));
        veterinario.setTitulo(txttitulo.getText());
        txtnombre.setText("");
        txtsueldo.setText("");
        txtcedula.setText("");
        txtapellido.setText("");
        txttitulo.setText("");
        txtedad.setText("");
        controladorveterinario.create(veterinario);
        txtcodigo.setText(Integer.toString(this.controladorveterinario.getCodigo()));
        JOptionPane.showMessageDialog(this, "Veterinario creado exitosamente", "Crear veterinario", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_botoncrearclienteActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoncrearcliente;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelapellido;
    private javax.swing.JLabel labelcedula;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labeldireccion;
    private javax.swing.JLabel labeledad;
    private javax.swing.JLabel labelgenero;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
