/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.veterinario;

import ec.edu.ups.Modelo.Veterinario;
import ec.edu.ups.controladores.ControladorVeterinario;
import ec.edu.ups.vista.VistaPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class EliminarVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EliminarVeterinario
     */
    private ControladorVeterinario controladorveterinario;
   public static String x;
    public EliminarVeterinario(ControladorVeterinario controladorveterinario) {
        initComponents();
        this.controladorveterinario = controladorveterinario;
        x="x";
         int a=VistaPrincipal.DesktopPane.getWidth()-this.getWidth();
        int b=VistaPrincipal.DesktopPane.getHeight()-this.getHeight();
        setLocation(a/2,b/2);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        labelcodigo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        labelnombre = new javax.swing.JLabel();
        labelapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        labelcedula = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        labeledad = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        labeldireccion = new javax.swing.JLabel();
        labelgenero = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        cancelar = new javax.swing.JButton();
        BE = new javax.swing.JButton();
        Aceptar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 162, 28));

        labelcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcodigo.setText("Código:");
        jPanel1.add(labelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        txtnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtnombre.setToolTipText("");
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 31));

        labelnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelnombre.setText("Nombre:");
        jPanel1.add(labelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        labelapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelapellido.setText("Apellido:");
        jPanel1.add(labelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        txtapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtapellido.setToolTipText("");
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 203, 29));

        txtcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcedula.setToolTipText("");
        txtcedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 196, 30));

        labelcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcedula.setText("Cedula:");
        jPanel1.add(labelcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 30));

        txtedad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtedad.setToolTipText("");
        txtedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 61, 29));

        labeledad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeledad.setText("Edad:");
        jPanel1.add(labeledad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 30));

        txtsueldo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtsueldo.setToolTipText("");
        txtsueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 196, 30));

        labeldireccion.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeldireccion.setText("Sueldo:");
        jPanel1.add(labeldireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        labelgenero.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelgenero.setText("Titulo:");
        jPanel1.add(labelgenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        txttitulo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txttitulo.setToolTipText("");
        txttitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 196, 31));

        cancelar.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 150, 40));

        BE.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        BE.setText("ELIMINAR");
        BE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEActionPerformed(evt);
            }
        });
        jPanel1.add(BE, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 170, 40));

        Aceptar1.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        Aceptar1.setText("Buscar");
        Aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 620, 290));

        jLabel1.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("ELIMINAR VETERINARIO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtcodigo.getText());
        controladorveterinario.delete(codigo);
        JOptionPane.showMessageDialog(this, "Veterinario eliminado exitosamente!!", "eliminar Veterinario" , JOptionPane.OK_OPTION);
        txtcodigo.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtcedula.setText("");
        txtedad.setText("");
        txtsueldo.setText("");
        txttitulo.setText("");
    }//GEN-LAST:event_BEActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void Aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar1ActionPerformed
        // TODO add your handling code here:
        String cedula = txtcedula.getText();
        Veterinario buscarv = controladorveterinario.readCedula(cedula);
        txtnombre.setText(buscarv.getNombre());
        txtapellido.setText(buscarv.getApellido());
        txtcodigo.setText(String.valueOf(buscarv.getCodigo()));
        txtedad.setText(String.valueOf(buscarv.getEdad()));
        txtsueldo.setText(String.valueOf(buscarv.getSueldo()));
        txttitulo.setText(buscarv.getTitulo());
    }//GEN-LAST:event_Aceptar1ActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar1;
    private javax.swing.JButton BE;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelapellido;
    private javax.swing.JLabel labelcedula;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labeldireccion;
    private javax.swing.JLabel labeledad;
    private javax.swing.JLabel labelgenero;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
