/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.veterinario;

import ec.edu.ups.Modelo.Veterinario;
import ec.edu.ups.controladores.ControladorVeterinario;
import ec.edu.ups.vista.VistaPrincipal;
import java.util.ResourceBundle;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class ModificarVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarVeterinario
     */
    private ControladorVeterinario controladorveterinario;
    public static String x;
    private ResourceBundle mensajes;

    public ModificarVeterinario(ControladorVeterinario controladorveterinario, ResourceBundle mensajes) {
        initComponents();
        this.controladorveterinario = controladorveterinario;
        x = "x";
        int a = VistaPrincipal.DesktopPane.getWidth() - this.getWidth();
        int b = VistaPrincipal.DesktopPane.getHeight() - this.getHeight();
        setLocation(a / 2, b / 2);
        setVisible(true);
        this.mensajes = mensajes;
        cambiarIdioma(mensajes);
    }

    public void cambiarIdioma(ResourceBundle mensajes) {
        labelm.setText(mensajes.getString("titulov.modificar"));
        labelcodigo.setText(mensajes.getString("veterinario.codigo"));
        labelnombre.setText(mensajes.getString("veterinario.nombre"));
        labelapellido.setText(mensajes.getString("veterinario.apellido"));
        labelcedula.setText(mensajes.getString("veterinario.cedula"));
        labeledad.setText(mensajes.getString("veterinario.edad"));
        labelsueldo.setText(mensajes.getString("veterinario.sueldo"));
        labeltitulo.setText(mensajes.getString("veterinario.titulo"));
        bb.setText(mensajes.getString("veterinario.bbuscar"));
        bc.setText(mensajes.getString("veterinario.bcancelar"));
        bm.setText(mensajes.getString("veterinario.bmodificar"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtcodigo = new javax.swing.JTextField();
        labelcodigo = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        labelnombre = new javax.swing.JLabel();
        labelapellido = new javax.swing.JLabel();
        txtapellido = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        labelcedula = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        labeledad = new javax.swing.JLabel();
        txtsueldo = new javax.swing.JTextField();
        labelsueldo = new javax.swing.JLabel();
        labeltitulo = new javax.swing.JLabel();
        txttitulo = new javax.swing.JTextField();
        bc = new javax.swing.JButton();
        bm = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        labelm = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtcodigo.setEnabled(false);
        jPanel1.add(txtcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 162, 28));

        labelcodigo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcodigo.setText("Código:");
        jPanel1.add(labelcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        txtnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtnombre.setToolTipText("");
        txtnombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 31));

        labelnombre.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelnombre.setText("Nombre:");
        jPanel1.add(labelnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        labelapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelapellido.setText("Apellido:");
        jPanel1.add(labelapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        txtapellido.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtapellido.setToolTipText("");
        txtapellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtapellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 203, 29));

        txtcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtcedula.setToolTipText("");
        txtcedula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 196, 30));

        labelcedula.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelcedula.setText("Cedula:");
        jPanel1.add(labelcedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, 30));

        txtedad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtedad.setToolTipText("");
        txtedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 61, 29));

        labeledad.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeledad.setText("Edad:");
        jPanel1.add(labeledad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 30));

        txtsueldo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txtsueldo.setToolTipText("");
        txtsueldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txtsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 196, 30));

        labelsueldo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labelsueldo.setText("Sueldo:");
        jPanel1.add(labelsueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        labeltitulo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        labeltitulo.setText("Titulo:");
        jPanel1.add(labeltitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        txttitulo.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        txttitulo.setToolTipText("");
        txttitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(txttitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 196, 31));

        bc.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        bc.setText("Cancelar");
        bc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcActionPerformed(evt);
            }
        });
        jPanel1.add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 150, 40));

        bm.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        bm.setText("Modificar");
        bm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmActionPerformed(evt);
            }
        });
        jPanel1.add(bm, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 40));

        bb.setFont(new java.awt.Font("Elephant", 2, 18)); // NOI18N
        bb.setText("Buscar");
        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        jPanel1.add(bb, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 140, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 650, 290));

        labelm.setFont(new java.awt.Font("Rockwell", 3, 48)); // NOI18N
        labelm.setText("MODIFICAR VETERINARIO");
        getContentPane().add(labelm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_bcActionPerformed

    private void bmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmActionPerformed
        // TODO add your handling code here:
        Veterinario veterinario = controladorveterinario.read(Integer.parseInt(txtcodigo.getText()));
        veterinario.setNombre(txtnombre.getText());
        veterinario.setApellido(txtapellido.getText());
        veterinario.setCedula(txtcedula.getText());
        veterinario.setEdad(Integer.parseInt(txtedad.getText()));
        veterinario.setSueldo(Double.valueOf(txtsueldo.getText()));
        veterinario.setTitulo(txttitulo.getText());
        controladorveterinario.update(veterinario);
        JOptionPane.showMessageDialog(this, "Veterinario actualizado exitosamente!!", "veterinario cliente", JOptionPane.OK_OPTION);
        txtcodigo.setText("");
        txtcedula.setText("");
        txtnombre.setText("");
        txtapellido.setText("");
        txtedad.setText("");
        txtsueldo.setText("");
        txttitulo.setText("");
    }//GEN-LAST:event_bmActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
        // TODO add your handling code here:
        String cedula = txtcedula.getText();
        Veterinario buscarv = controladorveterinario.readCedula(cedula);
        txtnombre.setText(buscarv.getNombre());
        txtapellido.setText(buscarv.getApellido());
        txtcodigo.setText(String.valueOf(buscarv.getCodigo()));
        txtedad.setText(String.valueOf(buscarv.getEdad()));
        txtsueldo.setText(String.valueOf(buscarv.getSueldo()));
        txttitulo.setText(buscarv.getTitulo());
    }//GEN-LAST:event_bbActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x = null;
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bb;
    private javax.swing.JButton bc;
    private javax.swing.JButton bm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelapellido;
    private javax.swing.JLabel labelcedula;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labeledad;
    private javax.swing.JLabel labelm;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelsueldo;
    private javax.swing.JLabel labeltitulo;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txttitulo;
    // End of variables declaration//GEN-END:variables
}
