/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.veterinario;

import ec.edu.ups.Modelo.Veterinario;
import ec.edu.ups.controladores.ControladorVeterinario;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class ModificarVeterinario extends javax.swing.JInternalFrame {

    /**
     * Creates new form ModificarVeterinario
     */
    private ControladorVeterinario controladorveterinario;
    public ModificarVeterinario(ControladorVeterinario controladorveterinario) {
        initComponents();
        this.controladorveterinario =controladorveterinario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigo1 = new javax.swing.JTextField();
        labelcodigo1 = new javax.swing.JLabel();
        txtnombre1 = new javax.swing.JTextField();
        labelnombre1 = new javax.swing.JLabel();
        labelapellido1 = new javax.swing.JLabel();
        txtapellido1 = new javax.swing.JTextField();
        txtcedula1 = new javax.swing.JTextField();
        labelcedula1 = new javax.swing.JLabel();
        txtedad1 = new javax.swing.JTextField();
        labeledad1 = new javax.swing.JLabel();
        txtsueldo1 = new javax.swing.JTextField();
        labeldireccion1 = new javax.swing.JLabel();
        labelgenero1 = new javax.swing.JLabel();
        txttitulo1 = new javax.swing.JTextField();
        cancelar1 = new javax.swing.JButton();
        Aceptar1 = new javax.swing.JButton();
        BM = new javax.swing.JButton();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("MODIFICAR VETERINARIO");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        txtcodigo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtcodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 162, 28));

        labelcodigo1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelcodigo1.setText("Código:");
        jPanel2.add(labelcodigo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, 30));

        txtnombre1.setToolTipText("");
        txtnombre1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 31));

        labelnombre1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelnombre1.setText("Nombre:");
        jPanel2.add(labelnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 30));

        labelapellido1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelapellido1.setText("Apellido:");
        jPanel2.add(labelapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        txtapellido1.setToolTipText("");
        txtapellido1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtapellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 203, 29));

        txtcedula1.setToolTipText("");
        txtcedula1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtcedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 196, 30));

        labelcedula1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelcedula1.setText("Cedula:");
        jPanel2.add(labelcedula1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 30));

        txtedad1.setToolTipText("");
        txtedad1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtedad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 61, 29));

        labeledad1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeledad1.setText("Edad:");
        jPanel2.add(labeledad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 30));

        txtsueldo1.setToolTipText("");
        txtsueldo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txtsueldo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 196, 30));

        labeldireccion1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labeldireccion1.setText("Sueldo:");
        jPanel2.add(labeldireccion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 30));

        labelgenero1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelgenero1.setText("Titulo:");
        jPanel2.add(labelgenero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 30));

        txttitulo1.setToolTipText("");
        txttitulo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(txttitulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 196, 31));

        cancelar1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        cancelar1.setForeground(new java.awt.Color(0, 255, 204));
        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });
        jPanel2.add(cancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 150, 40));

        Aceptar1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Aceptar1.setForeground(new java.awt.Color(0, 255, 204));
        Aceptar1.setText("Buscar");
        Aceptar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar1ActionPerformed(evt);
            }
        });
        jPanel2.add(Aceptar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 140, 30));

        BM.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BM.setText("Modificar");
        BM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BMActionPerformed(evt);
            }
        });
        jPanel2.add(BM, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        // TODO add your handling code here:

        dispose();
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void Aceptar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar1ActionPerformed
        // TODO add your handling code here:
        int codigo = Integer.parseInt(txtcodigo1.getText());
        Veterinario buscarv = controladorveterinario.read(codigo);
        txtnombre1.setText(buscarv.getNombre());
        txtapellido1.setText(buscarv.getApellido());
        txtcedula1.setText(buscarv.getCedula());
        txtedad1.setText(String.valueOf(buscarv.getEdad()));
        txtsueldo1.setText(String.valueOf(buscarv.getSueldo()));
        txttitulo1.setText(buscarv.getTitulo());
    }//GEN-LAST:event_Aceptar1ActionPerformed

    private void BMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BMActionPerformed
        // TODO add your handling code here:
        Veterinario modificar = controladorveterinario.read(Integer.parseInt(txtcodigo1.getText()));
        modificar.setNombre(txtnombre1.getText());
        modificar.setApellido(txtapellido1.getText());
        modificar.setCedula(txtcedula1.getText());
        modificar.setEdad(Integer.parseInt(txtedad1.getText()));
        modificar.setSueldo(Double.parseDouble(txtsueldo1.getText()));
       
        controladorveterinario.update(modificar);

        JOptionPane.showMessageDialog(this, "Veterinario Actualizado exitosamente", "Actualizar veterinario", JOptionPane.OK_OPTION);
        txtnombre1.setText("");
        txtapellido1.setText("");
        txtcedula1.setText("");
        txtedad1.setText("");
        txtsueldo1.setText("");
        txttitulo1.setText("");
    }//GEN-LAST:event_BMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar1;
    private javax.swing.JButton BM;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton cancelar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelapellido;
    private javax.swing.JLabel labelapellido1;
    private javax.swing.JLabel labelcedula;
    private javax.swing.JLabel labelcedula1;
    private javax.swing.JLabel labelcodigo;
    private javax.swing.JLabel labelcodigo1;
    private javax.swing.JLabel labeldireccion;
    private javax.swing.JLabel labeldireccion1;
    private javax.swing.JLabel labeledad;
    private javax.swing.JLabel labeledad1;
    private javax.swing.JLabel labelgenero;
    private javax.swing.JLabel labelgenero1;
    private javax.swing.JLabel labelnombre;
    private javax.swing.JLabel labelnombre1;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellido1;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcedula1;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigo1;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtedad1;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombre1;
    private javax.swing.JTextField txtsueldo;
    private javax.swing.JTextField txtsueldo1;
    private javax.swing.JTextField txttitulo;
    private javax.swing.JTextField txttitulo1;
    // End of variables declaration//GEN-END:variables
}
